spring:
  data:
    mongodb:
      host: 119.91.20.242
      database: game
      port: 17017
      username: game
      password: as123456
      authentication-database: admin

logging:
  level:
    com.lzh.game.framework.repository: debug
game:
  repository:
    cache-size: 3000
    cache-expire: 0
    clear-after-close: false

