spring:
  data:
    mongodb:
      host: localhost
      database: game
      port: 17217
  redis:
    redisson:
      config: classpath:redisson.yml

logging:
  level:
    com.lzh.game.repository: debug
game:
  repository:
    clear-redis-after-close: false

