spring:
  data:
    mongodb:
      host: 127.0.0.1
      database: game
      port: 27017
      username: game
      password: 123456
      authentication-database: admin

logging:
  level:
    com.lzh.game.framework.repository: debug
game:
  repository:
    cache-size: 3000
    cache-expire: 0
    clear-after-close: false

